<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Case Study: Working With Arab Barometer Surveys • retroharmonize</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Case Study: Working With Arab Barometer Surveys">
<meta property="og:description" content="retroharmonize">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">retroharmonize</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.1.16</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/afrobarometer.html">Case Study: Working With Afrobarometer surveys</a>
    </li>
    <li>
      <a href="../articles/arabbarometer.html">Case Study: Working With Arab Barometer Surveys</a>
    </li>
    <li>
      <a href="../articles/eurobarometer.html">Case Study: Working with Eurobarometer surveys</a>
    </li>
    <li>
      <a href="../articles/harmonize_labels.html">Harmonize Value Labels</a>
    </li>
    <li>
      <a href="../articles/labelled_spss_survey.html">The labelled_spss_survey class</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/rOpenGov/retroharmonize/">
    <span class="fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="arabbarometer_files/header-attrs-2.9/header-attrs.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Case Study: Working With Arab Barometer Surveys</h1>
                        <h4 class="author">Ahmed Shaibani</h4>
                        <h4 class="author">Daniel Antal</h4>
            
            <h4 class="date">2021-06-20</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/rOpenGov/retroharmonize/blob/master/vignettes/arabbarometer.Rmd"><code>vignettes/arabbarometer.Rmd</code></a></small>
      <div class="hidden name"><code>arabbarometer.Rmd</code></div>

    </div>

    
    
<pre><code>#&gt; [1] "C:/_packages/retroharmonize"</code></pre>
<p>The goal of this case study is to explore the variation in trust in various state institutions among African societies, as well as changes in trust over time.</p>
<p>To do this, we use data from <a href="https://https://www.arabbarometer.org/">Arab Barometer</a>, a nonpartisan research network that provides insight into the social, political, and economic attitudes and values of ordinary citizens across the Arab world.</p>
<p><code>retroharmonize</code> is not affiliated with Arab Barometer. To fully reproduce this example, you must acquire the data files from them, which is free of charge. If you download and use the survey data, the Arab Barometer does not take any responsibility for the results of the analysis of the Arab Barometer data. All results published using the Arab Barometer data and related content are responsibility of the respective author.</p>
<p>Some elements of the vignette are not “live”, because we want to avoid re-publishing the original microdata files from Arab Barometer. You can access the data directly from the <a href="https://www.arabbarometer.org/survey-data/data-downloads/">arabbarometer.org website</a> after agreeing to their <a href="https://www.arabbarometer.org/policies/">policies</a> and filling out a short questionnaire.</p>
<p>The files are stored on the website in <code>.zip</code> format, which may be extracted to folders. We assume that you extracted and copied all <code>.sav</code> files into a single folder that we will call in this vignette the <code>arabbarometer_dir</code>. Define your own <code>arabbarometer_dir</code> with <code><a href="https://rdrr.io/r/base/file.path.html">file.path()</a></code> in your own system.</p>
<table class="table">
<thead><tr class="header">
<th>File name</th>
<th>Wave</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>ABI_English.sav</td>
<td>Arab Barometer Wave I</td>
</tr>
<tr class="even">
<td>ABII_English.sav</td>
<td>Arab Barometer Wave II</td>
</tr>
<tr class="odd">
<td>ABIII_English.sav</td>
<td>Arab Barometer Wave III</td>
</tr>
<tr class="even">
<td>ABIV_English.sav</td>
<td>Arab Barometer Wave IV</td>
</tr>
<tr class="odd">
<td>AB-WaveV-EN.sav</td>
<td>Arab Barometer Wave V</td>
</tr>
</tbody>
</table>
<div id="importing-arab-barometer-files" class="section level2">
<h2 class="hasAnchor">
<a href="#importing-arab-barometer-files" class="anchor"></a>Importing Arab Barometer Files</h2>
<p>We start by reading in the three rounds of the Arab Barometer. We start by reading in the three rounds of the Arab Barometer. The following chunk is not evaluated, if you want to re-run this tutorial, you need to define your <code>arabbarometer_dir</code> and download the Arab Barometer files there, after acknowledging Arab Barometer’s terms and conditions.</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">### use here your own &lt;arabbarometer_dir&gt; directory</span>
<span class="va">ab</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.files.html">dir</a></span><span class="op">(</span><span class="va">arabbarometer_dir</span>, pattern <span class="op">=</span> <span class="st">"sav$"</span><span class="op">)</span>
<span class="va">arabbarometer_rounds</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/file.path.html">file.path</a></span><span class="op">(</span><span class="va">arabbarometer_dir</span>, <span class="va">ab</span><span class="op">)</span>
<span class="va">arab_waves</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/read_surveys.html">read_surveys</a></span><span class="op">(</span><span class="va">arabbarometer_rounds</span>, .f<span class="op">=</span><span class="st">'read_spss'</span><span class="op">)</span></code></pre></div>
<p>we appended meaningful identifiers to the file names as follows (you must follow the ordering of your files in your own <code>arabbarometer_dir</code> dir:</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/attr.html">attr</a></span><span class="op">(</span><span class="va">arab_waves</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span>,<span class="st">"id"</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="st">"Arab_Barometer_5"</span>
<span class="fu"><a href="https://rdrr.io/r/base/attr.html">attr</a></span><span class="op">(</span><span class="va">arab_waves</span><span class="op">[[</span><span class="fl">2</span><span class="op">]</span><span class="op">]</span>,<span class="st">"id"</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="st">"Arab_Barometer_1"</span>
<span class="fu"><a href="https://rdrr.io/r/base/attr.html">attr</a></span><span class="op">(</span><span class="va">arab_waves</span><span class="op">[[</span><span class="fl">3</span><span class="op">]</span><span class="op">]</span>,<span class="st">"id"</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="st">"Arab_Barometer_2"</span>
<span class="fu"><a href="https://rdrr.io/r/base/attr.html">attr</a></span><span class="op">(</span><span class="va">arab_waves</span><span class="op">[[</span><span class="fl">4</span><span class="op">]</span><span class="op">]</span>,<span class="st">"id"</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="st">"Arab_Barometer_3"</span>
<span class="fu"><a href="https://rdrr.io/r/base/attr.html">attr</a></span><span class="op">(</span><span class="va">arab_waves</span><span class="op">[[</span><span class="fl">5</span><span class="op">]</span><span class="op">]</span>,<span class="st">"id"</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="st">"Arab_Barometer_4"</span>
<span class="fu"><a href="https://rdrr.io/r/base/save.html">save</a></span><span class="op">(</span> <span class="va">arab_waves</span>, file <span class="op">=</span> <span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org//reference/here.html">here</a></span><span class="op">(</span><span class="st">"data-raw"</span>, <span class="st">"arab_waves.rda"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/load.html">load</a></span> <span class="op">(</span> <span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org//reference/here.html">here</a></span><span class="op">(</span><span class="st">"data-raw"</span>, <span class="st">"arab_waves.rda"</span><span class="op">)</span> <span class="op">)</span></code></pre></div>
<div id="importing-arabbarometer-datasets" class="section level3">
<h3 class="hasAnchor">
<a href="#importing-arabbarometer-datasets" class="anchor"></a>Importing Arabbarometer Datasets</h3>
<p>We used <code><a href="../reference/document_waves.html">document_waves()</a></code>to see the primary descriptive information of our survey wave (one harmonized survey set) files. Visually check that the file names correspond with the meaningful IDs that you gave to each survey wave, i.e., <code>Arab_Barometer_1</code> corresponds with <code>ABI_English.sav</code>.</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">documented_arab_waves</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/document_waves.html">document_waves</a></span><span class="op">(</span><span class="va">arab_waves</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">documented_arab_waves</span><span class="op">)</span>
<span class="co">#&gt; # A tibble: 5 x 5</span>
<span class="co">#&gt;   id               filename           ncol  nrow object_size</span>
<span class="co">#&gt;   &lt;chr&gt;            &lt;chr&gt;             &lt;int&gt; &lt;int&gt;       &lt;dbl&gt;</span>
<span class="co">#&gt; 1 Arab_Barometer_5 AB-WaveV-EN.sav     348 26780    78131600</span>
<span class="co">#&gt; 2 Arab_Barometer_1 ABI_English.sav     182  7337    12089512</span>
<span class="co">#&gt; 3 Arab_Barometer_2 ABII_English.sav    469 12782    51603152</span>
<span class="co">#&gt; 4 Arab_Barometer_3 ABIII_English.sav   297 14809    37826816</span>
<span class="co">#&gt; 5 Arab_Barometer_4 ABIV_English.sav    291  9000    23315888</span></code></pre></div>
<p>We obtained 5 nested lists in the <code>arab_waves</code> list, each of them containing data of one survey wave Arab Barometer. To create longitudinal tables, i.e., join several survey waves into a single table, it is important to review the methodology of each round of Arabbarometric’s surveys, its structure, modifications, and changes in topics of interest.</p>
</div>
<div id="merged-metadata-creation" class="section level3">
<h3 class="hasAnchor">
<a href="#merged-metadata-creation" class="anchor"></a>Merged Metadata Creation</h3>
<p>In this step, we built a comprehensive metadata table that maps information about variable names and labels of the case’s surveys data. Each row in the table above refers to a different variable in the survey data file. This is accomplished using the <code><a href="../reference/metadata_create.html">metadata_create()</a></code> function, which collects metadata from survey data files, normalizes variable labels, and defines substantive response ranges and missing value codes.</p>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">arabb_metadata</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span> <span class="op">(</span> X <span class="op">=</span> <span class="va">arab_waves</span>, FUN <span class="op">=</span> <span class="va">metadata_create</span><span class="op">)</span>
<span class="va">arabb_metadata</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/do.call.html">do.call</a></span><span class="op">(</span><span class="va">rbind</span>, <span class="va">arabb_metadata</span><span class="op">)</span></code></pre></div>
<p>Let’s randomly review some metadata:</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">2021</span><span class="op">)</span>
<span class="va">arabb_metadata</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span> <span class="op">(</span><span class="op">-</span><span class="fu"><a href="https://tidyselect.r-lib.org/reference/all_of.html">all_of</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"filename"</span>, <span class="st">"class_orig"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/sample_n.html">sample_n</a></span><span class="op">(</span><span class="fl">10</span><span class="op">)</span>
<span class="co">#&gt;                  id var_name_orig</span>
<span class="co">#&gt; 1  Arab_Barometer_2         q7112</span>
<span class="co">#&gt; 2  Arab_Barometer_5        Q521_1</span>
<span class="co">#&gt; 3  Arab_Barometer_4    aid1b1lang</span>
<span class="co">#&gt; 4  Arab_Barometer_1         q2572</span>
<span class="co">#&gt; 5  Arab_Barometer_2         q5164</span>
<span class="co">#&gt; 6  Arab_Barometer_2         eg802</span>
<span class="co">#&gt; 7  Arab_Barometer_3           sex</span>
<span class="co">#&gt; 8  Arab_Barometer_3         q5013</span>
<span class="co">#&gt; 9  Arab_Barometer_5         Q860B</span>
<span class="co">#&gt; 10 Arab_Barometer_2         eg814</span>
<span class="co">#&gt;                                                                                                                                                  label_orig</span>
<span class="co">#&gt; 1  q7112 to what extent do you agree or disagree with the following statements 2 in order to eliminate global terrorism, the palestine issue must be solved</span>
<span class="co">#&gt; 2                                                                                                                    guaranteed freedoms opinion expression</span>
<span class="co">#&gt; 3                                                                                                        aid1b1 respondent participated in language program</span>
<span class="co">#&gt; 4                                                                                      q257 2 can you remember the name of the speaker leader of parliament</span>
<span class="co">#&gt; 5  q5164 to what extent do you agree or disagree with the following statements 4 a democratic system may have problems, yet it is better than other systems</span>
<span class="co">#&gt; 6                                 eg802 did you participate in the protests against former president hosni mubarak between january 25 and february 11, 2011</span>
<span class="co">#&gt; 7                                                                                                                                                       sex</span>
<span class="co">#&gt; 8                                                                                         q501 3 are you a member of a professional association trade union</span>
<span class="co">#&gt; 9                                                                                                                                                      null</span>
<span class="co">#&gt; 10                                                                       eg814 in the coming time period, do you prefer the political system in egypt to be</span>
<span class="co">#&gt;                 labels        valid_labels na_labels na_range n_labels</span>
<span class="co">#&gt; 1  0, 1, 2, 3, 4, 8, 9 0, 1, 2, 3, 4, 8, 9                 NA        7</span>
<span class="co">#&gt; 2   1, 2, 3, 4, 98, 99  1, 2, 3, 4, 98, 99                 NA        6</span>
<span class="co">#&gt; 3                 0, 1                0, 1                 NA        2</span>
<span class="co">#&gt; 4     1, 2, 97, 98, 99    1, 2, 97, 98, 99                 NA        5</span>
<span class="co">#&gt; 5  0, 1, 2, 3, 4, 8, 9 0, 1, 2, 3, 4, 8, 9                 NA        7</span>
<span class="co">#&gt; 6        0, 1, 2, 8, 9       0, 1, 2, 8, 9                 NA        5</span>
<span class="co">#&gt; 7                 1, 2                1, 2                 NA        2</span>
<span class="co">#&gt; 8        0, 1, 2, 8, 9       0, 1, 2, 8, 9                 NA        5</span>
<span class="co">#&gt; 9                   NA                  NA        NA       NA        0</span>
<span class="co">#&gt; 10    0, 1, 2, 3, 8, 9    0, 1, 2, 3, 8, 9                 NA        6</span>
<span class="co">#&gt;    n_valid_labels n_na_labels</span>
<span class="co">#&gt; 1               7           0</span>
<span class="co">#&gt; 2               6           0</span>
<span class="co">#&gt; 3               2           0</span>
<span class="co">#&gt; 4               5           0</span>
<span class="co">#&gt; 5               7           0</span>
<span class="co">#&gt; 6               5           0</span>
<span class="co">#&gt; 7               2           0</span>
<span class="co">#&gt; 8               5           0</span>
<span class="co">#&gt; 9               0           0</span>
<span class="co">#&gt; 10              6           0</span></code></pre></div>
<p>We select from the metadata file <code>rowid</code> being the unique case identifier, and variables of interest: <code>date</code> with the interview date,<code>COUNTRY</code> containing information about the country where the interview was conducted, and with <code>wt</code> being the weighting factor, and some “real” survey questions.</p>
<p>In the same context, you should also carefully insert key words and expressions that match with your survey questionnaire item of interest; in our case, we chose <em>Election, parliamentary</em>, and <em>Election</em> to fork an exact question about parliamentary election, which is <code>How would you evaluate the last parliamentary election?</code></p>
<p>The variable names (var_name) and labels (var_label) then must be normalized and harmonized.</p>
</div>
<div id="harmonizing-the-variable-names" class="section level3">
<h3 class="hasAnchor">
<a href="#harmonizing-the-variable-names" class="anchor"></a>Harmonizing the variable names</h3>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R">
<span class="va">to_harmonize</span> <span class="op">&lt;-</span> <span class="va">arabb_metadata</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span> <span class="va">.data</span><span class="op">$</span><span class="va">var_name_orig</span> <span class="op">%in%</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"rowid"</span>, <span class="st">"country"</span>,<span class="st">"date"</span>, <span class="st">"wt"</span><span class="op">)</span><span class="op">|</span>
           <span class="fu"><a href="https://rdrr.io/r/base/grep.html">grepl</a></span><span class="op">(</span><span class="st">"how would you evaluate the last parliamentary"</span>, <span class="va">.data</span><span class="op">$</span><span class="va">label_orig</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>var_label <span class="op">=</span> <span class="fu"><a href="../reference/label_normalize.html">var_label_normalize</a></span><span class="op">(</span><span class="va">.data</span><span class="op">$</span><span class="va">label_orig</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>var_label <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/case_when.html">case_when</a></span><span class="op">(</span>
    <span class="va">.data</span><span class="op">$</span><span class="va">var_name_orig</span> <span class="op">==</span> <span class="st">"country"</span> <span class="op">~</span> <span class="st">"Country"</span>,
    <span class="va">.data</span><span class="op">$</span><span class="va">var_name_orig</span> <span class="op">==</span> <span class="st">"rowid"</span>   <span class="op">~</span> <span class="st">"Unique ID AB English"</span>, <span class="co"># in pdf Unique ID AB English</span>
    <span class="va">.data</span><span class="op">$</span><span class="va">var_name_orig</span> <span class="op">==</span> <span class="st">"date"</span>    <span class="op">~</span> <span class="st">"Date_of_interview"</span>,
    <span class="va">.data</span><span class="op">$</span><span class="va">var_name_orig</span> <span class="op">==</span> <span class="st">"wt"</span>      <span class="op">~</span> <span class="st">"Weight"</span>,
    <span class="cn">TRUE</span> <span class="op">~</span> <span class="st">" Evaluation in the last parliamentary elections"</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span> <span class="op">(</span> var_name <span class="op">=</span> <span class="fu"><a href="../reference/label_normalize.html">var_label_normalize</a></span><span class="op">(</span><span class="va">.data</span><span class="op">$</span><span class="va">var_label</span><span class="op">)</span> <span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">2021</span><span class="op">)</span> <span class="co"># Let's see the same random example:</span>
<span class="fu"><a href="https://dplyr.tidyverse.org/reference/sample_n.html">sample_n</a></span><span class="op">(</span><span class="va">to_harmonize</span><span class="op">%&gt;%</span> 
       <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span> <span class="op">(</span> <span class="fu"><a href="https://tidyselect.r-lib.org/reference/all_of.html">all_of</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"id"</span>, <span class="st">"var_name"</span>, <span class="st">"var_label"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>, <span class="fl">10</span><span class="op">)</span>
<span class="co">#&gt;                  id                                       var_name</span>
<span class="co">#&gt; 1  Arab_Barometer_2                           unique id ab english</span>
<span class="co">#&gt; 2  Arab_Barometer_1                                        country</span>
<span class="co">#&gt; 3  Arab_Barometer_3                                         weight</span>
<span class="co">#&gt; 4  Arab_Barometer_2                                         weight</span>
<span class="co">#&gt; 5  Arab_Barometer_4 evaluation in the last parliamentary elections</span>
<span class="co">#&gt; 6  Arab_Barometer_3                                        country</span>
<span class="co">#&gt; 7  Arab_Barometer_5                              date_of_interview</span>
<span class="co">#&gt; 8  Arab_Barometer_4                                         weight</span>
<span class="co">#&gt; 9  Arab_Barometer_4                                        country</span>
<span class="co">#&gt; 10 Arab_Barometer_3                           unique id ab english</span>
<span class="co">#&gt;                                          var_label</span>
<span class="co">#&gt; 1                             Unique ID AB English</span>
<span class="co">#&gt; 2                                          Country</span>
<span class="co">#&gt; 3                                           Weight</span>
<span class="co">#&gt; 4                                           Weight</span>
<span class="co">#&gt; 5   Evaluation in the last parliamentary elections</span>
<span class="co">#&gt; 6                                          Country</span>
<span class="co">#&gt; 7                                Date_of_interview</span>
<span class="co">#&gt; 8                                           Weight</span>
<span class="co">#&gt; 9                                          Country</span>
<span class="co">#&gt; 10                            Unique ID AB English</span></code></pre></div>
<p>The function <code><a href="../reference/merge_waves.html">merge_waves()</a></code> harmonizes the variable names, the variable labels and survey identifiers and returns a list of surveys (of <code>class survey()</code>.) The parameter <em>var_harmonization</em> must be a list or a data frame that contains at least the original file name (<code>filename</code>), original variable names (<code>var_name_orig</code>), the new variable names (<code>var_name</code>) and their labels (var_label), so that the function correctly makes the harmonization steps.</p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R">
<span class="va">merged_ab</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/merge_waves.html">merge_waves</a></span><span class="op">(</span>waves <span class="op">=</span> <span class="va">arab_waves</span>, 
                         var_harmonization <span class="op">=</span> <span class="va">to_harmonize</span><span class="op">)</span>

<span class="va">merged_ab</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span> <span class="op">(</span><span class="va">merged_ab</span>, 
                     FUN <span class="op">=</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="va">x</span>  <span class="op">%&gt;%</span>
                       <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span> country <span class="op">=</span> <span class="fu"><a href="../reference/labelled_spss_survey.html">as_character</a></span><span class="op">(</span><span class="va">country</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># cleaning country names using the second round</span>
<span class="va">merged_ab</span><span class="op">[[</span><span class="fl">2</span><span class="op">]</span><span class="op">]</span><span class="op">$</span><span class="va">country</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/grep.html">gsub</a></span><span class="op">(</span><span class="st">"\\d{1,}\\.\\s?"</span>,<span class="st">""</span>,<span class="va">merged_ab</span><span class="op">[[</span><span class="fl">2</span><span class="op">]</span><span class="op">]</span><span class="op">$</span><span class="va">country</span><span class="op">)</span>
<span class="va">merged_ab</span><span class="op">[[</span><span class="fl">2</span><span class="op">]</span><span class="op">]</span><span class="op">$</span><span class="va">country</span> <span class="op">&lt;-</span> <span class="fu">str_squish</span><span class="op">(</span><span class="va">merged_ab</span><span class="op">[[</span><span class="fl">2</span><span class="op">]</span><span class="op">]</span><span class="op">$</span><span class="va">country</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">documented_merged_ab</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/document_waves.html">document_waves</a></span><span class="op">(</span><span class="va">merged_ab</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">documented_merged_ab</span><span class="op">)</span>
<span class="co">#&gt; # A tibble: 5 x 5</span>
<span class="co">#&gt;   id               filename           ncol  nrow object_size</span>
<span class="co">#&gt;   &lt;chr&gt;            &lt;chr&gt;             &lt;int&gt; &lt;int&gt;       &lt;dbl&gt;</span>
<span class="co">#&gt; 1 Arab_Barometer_5 AB-WaveV-EN.sav       4 26780     2986800</span>
<span class="co">#&gt; 2 Arab_Barometer_1 ABI_English.sav       2  7337      690576</span>
<span class="co">#&gt; 3 Arab_Barometer_2 ABII_English.sav      4 12782     1437856</span>
<span class="co">#&gt; 4 Arab_Barometer_3 ABIII_English.sav     5 14809     1785672</span>
<span class="co">#&gt; 5 Arab_Barometer_4 ABIV_English.sav      4  9000     1013488</span></code></pre></div>
<p>Let’s take a look at the variables:</p>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span> <span class="op">(</span><span class="va">merged_ab</span>, <span class="va">names</span><span class="op">)</span>
<span class="co">#&gt; [[1]]</span>
<span class="co">#&gt; [1] "unique id ab english" "country"              "weight"              </span>
<span class="co">#&gt; [4] "date_of_interview"   </span>
<span class="co">#&gt; </span>
<span class="co">#&gt; [[2]]</span>
<span class="co">#&gt; [1] "unique id ab english" "country"             </span>
<span class="co">#&gt; </span>
<span class="co">#&gt; [[3]]</span>
<span class="co">#&gt; [1] "unique id ab english"                          </span>
<span class="co">#&gt; [2] "country"                                       </span>
<span class="co">#&gt; [3] "evaluation in the last parliamentary elections"</span>
<span class="co">#&gt; [4] "weight"                                        </span>
<span class="co">#&gt; </span>
<span class="co">#&gt; [[4]]</span>
<span class="co">#&gt; [1] "unique id ab english"                          </span>
<span class="co">#&gt; [2] "country"                                       </span>
<span class="co">#&gt; [3] "date_of_interview"                             </span>
<span class="co">#&gt; [4] "weight"                                        </span>
<span class="co">#&gt; [5] "evaluation in the last parliamentary elections"</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; [[5]]</span>
<span class="co">#&gt; [1] "unique id ab english"                          </span>
<span class="co">#&gt; [2] "country"                                       </span>
<span class="co">#&gt; [3] "weight"                                        </span>
<span class="co">#&gt; [4] "evaluation in the last parliamentary elections"</span></code></pre></div>
<p>We see that they are not set in a standard format (variable names should not have spaces for programmatic use). We apply snakecase variable naming:</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">require</a></span><span class="op">(</span><span class="va"><a href="https://github.com/Tazinho/snakecase">snakecase</a></span><span class="op">)</span>
<span class="co"># replace space with underscore form variable names</span>
<span class="va">merged_ab</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="va">merged_ab</span>,
                    FUN <span class="op">=</span> <span class="kw">function</span><span class="op">(</span><span class="va">df</span><span class="op">)</span> <span class="va">df</span> <span class="op">%&gt;%</span>
                      <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select_all.html">rename_all</a></span><span class="op">(</span><span class="fu">snakecase</span><span class="fu">::</span><span class="va"><a href="https://rdrr.io/pkg/snakecase/man/caseconverter.html">to_snake_case</a></span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>Now the variable names are ready to use in the programmatic way:</p>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="va">merged_ab</span>, <span class="va">names</span><span class="op">)</span>
<span class="co">#&gt; [[1]]</span>
<span class="co">#&gt; [1] "unique_id_ab_english" "country"              "weight"              </span>
<span class="co">#&gt; [4] "date_of_interview"   </span>
<span class="co">#&gt; </span>
<span class="co">#&gt; [[2]]</span>
<span class="co">#&gt; [1] "unique_id_ab_english" "country"             </span>
<span class="co">#&gt; </span>
<span class="co">#&gt; [[3]]</span>
<span class="co">#&gt; [1] "unique_id_ab_english"                          </span>
<span class="co">#&gt; [2] "country"                                       </span>
<span class="co">#&gt; [3] "evaluation_in_the_last_parliamentary_elections"</span>
<span class="co">#&gt; [4] "weight"                                        </span>
<span class="co">#&gt; </span>
<span class="co">#&gt; [[4]]</span>
<span class="co">#&gt; [1] "unique_id_ab_english"                          </span>
<span class="co">#&gt; [2] "country"                                       </span>
<span class="co">#&gt; [3] "date_of_interview"                             </span>
<span class="co">#&gt; [4] "weight"                                        </span>
<span class="co">#&gt; [5] "evaluation_in_the_last_parliamentary_elections"</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; [[5]]</span>
<span class="co">#&gt; [1] "unique_id_ab_english"                          </span>
<span class="co">#&gt; [2] "country"                                       </span>
<span class="co">#&gt; [3] "weight"                                        </span>
<span class="co">#&gt; [4] "evaluation_in_the_last_parliamentary_elections"</span></code></pre></div>
<p>As shown from the table above, we obtained a reduced form of a comprehensive metadata in nested data set format.</p>
<p>It is useful to check the variable names in each round, and filter out nonessential variables and if the full round data does not have the question of our interest, the omitting the round is possible.</p>
<p>In our case, we decided to: - omit completely both waves 1 and 5, because none of them has our key variable <code>Parliamentary Election Evaluation</code>; - omit <code>date of interview</code> as it is missing in both waves (rounds) 2 and 4.</p>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">merged_ab</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="cn">NULL</span> <span class="co"># Remove AB-WaveV-EN_1</span>
<span class="va">merged_ab</span><span class="op">[[</span><span class="fl">2</span><span class="op">]</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="cn">NULL</span> <span class="co"># Remove ABI_English</span></code></pre></div>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">merged_arabb</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="va">merged_ab</span>, <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">{</span>
  <span class="kw">if</span> <span class="op">(</span><span class="st">"date_of_interview"</span> <span class="op">%in%</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">)</span><span class="op">{</span>
    <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">x</span>, select <span class="op">=</span> <span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">date_of_interview</span><span class="op">)</span><span class="op">)</span>
  <span class="op">}</span> <span class="kw">else</span><span class="op">{</span>
    <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span>
  <span class="op">}</span>
<span class="op">}</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/document_waves.html">document_waves</a></span><span class="op">(</span><span class="va">merged_arabb</span><span class="op">)</span>
<span class="co">#&gt; # A tibble: 3 x 5</span>
<span class="co">#&gt;   id               filename           ncol  nrow object_size</span>
<span class="co">#&gt;   &lt;chr&gt;            &lt;chr&gt;             &lt;int&gt; &lt;int&gt;       &lt;dbl&gt;</span>
<span class="co">#&gt; 1 Arab_Barometer_1 ABI_English.sav       2  7337      690576</span>
<span class="co">#&gt; 2 Arab_Barometer_3 ABIII_English.sav     4 14809     1666176</span>
<span class="co">#&gt; 3 Arab_Barometer_4 ABIV_English.sav      4  9000     1013488</span></code></pre></div>
</div>
<div id="variable-label-harmonization" class="section level3">
<h3 class="hasAnchor">
<a href="#variable-label-harmonization" class="anchor"></a>Variable Label Harmonization</h3>
<p>The question of interest “how would you evaluate the last parliamentary election?” is described as a closed form survey questions where answers are predetermined and the respondents chose one of the answer options. This question has four-point ordinal scales, therefore, data is best to be analyzed with ordinal models which do not assume that the points are equidistant, i.e. as factors.</p>
<p>In order to get a quick idea of how the data look like, we assigned numbers 1-4 as follows:</p>
<ol style="list-style-type: decimal">
<li>Answer with 1 corresponding to the <code>free_and_fair</code> (highest democratic election process).</li>
<li>Answer with 2 corresponding to <code>some_minor_problems</code>.</li>
<li>Answer with 3 corresponding to <code>some_major_problems</code>.</li>
<li>Answer with 4 corresponding to <code>not_free</code>(lowest democratic election process).</li>
<li>Answer with other values like 0 and higher than 4 is classified as either missing answers, do not know or refuse/declined to answers.</li>
</ol>
</div>
<div id="harmonizing-the-missing-values" class="section level3">
<h3 class="hasAnchor">
<a href="#harmonizing-the-missing-values" class="anchor"></a>Harmonizing the Missing Values</h3>
<p>Arabbarometer’s SPSS files use various missing value categories, wo we have to carefully harmonize them, too. The entire value range is the following:</p>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/collect_val_labels.html">collect_val_labels</a></span><span class="op">(</span>
  <span class="va">to_harmonize</span> <span class="op">%&gt;%</span> 
     <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/grep.html">grepl</a></span><span class="op">(</span><span class="st">"evaluation in the last parliamentary elections"</span>, 
                  <span class="va">.data</span><span class="op">$</span><span class="va">var_name</span><span class="op">)</span><span class="op">)</span>
  <span class="op">)</span>
<span class="co">#&gt;  [1] "0. missing"                                          </span>
<span class="co">#&gt;  [2] "1. they were completely free and fair"               </span>
<span class="co">#&gt;  [3] "2. they were free and fair, with some minor problems"</span>
<span class="co">#&gt;  [4] "3. they were free and fair, with some major problems"</span>
<span class="co">#&gt;  [5] "4. they were not free and fair"                      </span>
<span class="co">#&gt;  [6] "8. i don't know"                                     </span>
<span class="co">#&gt;  [7] "9. declined to answer"                               </span>
<span class="co">#&gt;  [8] "Missing"                                             </span>
<span class="co">#&gt;  [9] "They were completely free and fair"                  </span>
<span class="co">#&gt; [10] "They were free and fair, with some minor breaches"   </span>
<span class="co">#&gt; [11] "They were free and fair, with some major breaches"   </span>
<span class="co">#&gt; [12] "They were not free and fair"                         </span>
<span class="co">#&gt; [13] "Don't know"                                          </span>
<span class="co">#&gt; [14] "Refuse"                                              </span>
<span class="co">#&gt; [15] "Completely free and fair"                            </span>
<span class="co">#&gt; [16] "Free and fair, but with minor problems"              </span>
<span class="co">#&gt; [17] "Free and fair, with major problems"                  </span>
<span class="co">#&gt; [18] "Not free or fair"                                    </span>
<span class="co">#&gt; [19] "Don't know (Do not read)"                            </span>
<span class="co">#&gt; [20] "Decline to answer (Do not read)"</span></code></pre></div>
<blockquote>
<p>It is crucial to draw attention to special cases when some <code>NA</code> values are not labeled profoundly in data tables, thus, we decided to replace <code>NA</code> in advance with the value of the “missing/or not applicable” before standardizing response’s values. Notice that we assigned original <code>NA</code> or missing labels with numerical values as in the table below:</p>
</blockquote>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R">
<span class="va">missing_value_labels</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"do_not_know"</span>,<span class="st">"declined"</span>,<span class="st">"declined"</span>,<span class="st">"missing"</span><span class="op">)</span>
<span class="va">missing_value_codes</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"99997"</span>,<span class="st">"99998"</span>,<span class="st">"99998"</span>,<span class="st">"99999"</span><span class="op">)</span>

<span class="va">na_harmonized_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>
  original_label <span class="op">=</span> <span class="va">missing_value_labels</span>,
  harmonized_values <span class="op">=</span> <span class="va">missing_value_codes</span>,
  stringsAsFactors <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>

<span class="va">na_harmonized_df</span>
<span class="co">#&gt;   original_label harmonized_values</span>
<span class="co">#&gt; 1    do_not_know             99997</span>
<span class="co">#&gt; 2       declined             99998</span>
<span class="co">#&gt; 3       declined             99998</span>
<span class="co">#&gt; 4        missing             99999</span></code></pre></div>
<p>For safety, we need to handle the <code>NA</code> values before harmonization (this is important), as function harmonize_arabb_trust could not distinguish NA if not labeled. so it is better to replace N/A immediately with the value of the “missing/or not applicable” before standardizing response’ values. we could add label to N/A after adding the values but her not necessary.</p>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## This is not code</span>
<span class="va">merged_arabb</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="va">merged_arabb</span>, <span class="kw">function</span><span class="op">(</span><span class="va">df</span><span class="op">)</span> <span class="op">{</span>
  <span class="va">df</span><span class="op">$</span><span class="va">evaluation_in_the_last_parliamentary_elections</span><span class="op">[</span>
    <span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">df</span><span class="op">$</span><span class="va">evaluation_in_the_last_parliamentary_elections</span><span class="op">)</span><span class="op">==</span><span class="cn">T</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fl">99999</span>
  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="va">df</span><span class="op">)</span>
<span class="op">}</span> <span class="op">)</span>
<span class="co"># merged_arabb[[3]]$evaluation_in_the_last_parliamentary_elections[is.na(merged_arabb[[3]]$evaluation_in_the_last_parliamentary_elections)==T]&lt;-99999 </span>
<span class="co"># merged_arabb[[1]]$evaluation_in_the_last_parliamentary_elections[is.na(merged_arabb[[1]]$evaluation_in_the_last_parliamentary_elections)==T]&lt;-99999 </span>
<span class="co"># merged_arabb[[2]]$evaluation_in_the_last_parliamentary_elections[is.na(merged_arabb[[2]]$evaluation_in_the_last_parliamentary_elections)==T]&lt;-99999 </span></code></pre></div>
<p>The harmonization function from the <code><a href="../reference/harmonize_values.html">harmonize_values()</a></code> is a prototype function. In fact, this is just a re-setting the default values of the original function. It makes future reference in pipelines easier, or it can be used for a question block only, in this case to variables the are correlated to our question about (“Evaluation of the Parliamentary Election”).</p>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">harmonize_arabb_trust</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">{</span>
  <span class="va">label_list</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>
    from <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"(\\d\\.\\s)?(\\w+\\s\\w+\\s)?([c|C]ompletely free and fair)"</span>,
             <span class="st">"(.+)(but)?\\s?(with)\\s(some)?\\s{0,}(minor\\s\\w+)"</span>,
             <span class="st">"(.+)(but)?\\s?(with)\\s(some)?\\s{0,}(major\\s\\w+)"</span>,
             <span class="st">"(.+)?([n|N]ot\\sfree\\s\\w+\\s\\w+)"</span>,
             <span class="st">"((\\d.\\s{0,})?\\si\\s)?([d|D]on.t\\sknow)(\\s\\(Do\\snot\\sread\\))?"</span>, 
             <span class="st">"[R|r]efuse"</span>, 
             <span class="st">"(\\d.\\s)?[d|D]ecline[d]?(\\s\\w+\\s\\w+)(\\s.Do not read.)?"</span>,
             <span class="st">"(\\d.\\s)?[m|M]issing"</span><span class="op">)</span>,
    to <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"free_and_fair"</span>, 
           <span class="st">"some_minor_problems"</span>,
           <span class="st">"some_major_problems"</span>,
           <span class="st">"not_free"</span>,
           <span class="st">"do_not_know"</span>,<span class="st">"declined"</span>,<span class="st">"declined"</span>,<span class="st">"missing"</span><span class="op">)</span>,
    numeric_values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>,<span class="fl">2</span>,<span class="fl">1</span>,<span class="fl">0</span>,<span class="fl">99997</span>,<span class="fl">99998</span>,<span class="fl">99998</span>,<span class="fl">99999</span><span class="op">)</span><span class="op">)</span>
  <span class="fu"><a href="../reference/harmonize_values.html">harmonize_values</a></span><span class="op">(</span><span class="va">x</span>, harmonize_labels <span class="op">=</span> <span class="va">label_list</span>, 
                   na_values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"do_not_know"</span><span class="op">=</span> <span class="fl">99997</span>,
                                 <span class="st">"declined"</span><span class="op">=</span><span class="fl">99998</span>,
                                 <span class="st">"missing"</span><span class="op">=</span><span class="fl">99999</span>
                   <span class="op">)</span><span class="op">)</span>
<span class="op">}</span></code></pre></div>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">harmonized_arabb_waves</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/harmonize_waves.html">harmonize_waves</a></span><span class="op">(</span> 
  waves <span class="op">=</span> <span class="va">merged_arabb</span>, 
  .f <span class="op">=</span> <span class="va">harmonize_arabb_trust</span> <span class="op">)</span></code></pre></div>
<p>We tested the transformed variables after applying the harmonization function, and we obtained the following counting summary of each unique answer of our question.</p>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">harmonized_arabb_waves</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span> <span class="op">(</span> weight <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">.data</span><span class="op">$</span><span class="va">weight</span><span class="op">)</span>, <span class="fl">1</span>, <span class="va">.data</span><span class="op">$</span><span class="va">weight</span><span class="op">)</span>, 
           evaluation_in_the_last_parliamentary_elections <span class="op">=</span> <span class="fu"><a href="../reference/as_factor.html">as_factor</a></span><span class="op">(</span><span class="va">evaluation_in_the_last_parliamentary_elections</span><span class="op">)</span>, 
           country <span class="op">=</span> <span class="fu"><a href="../reference/as_factor.html">as_factor</a></span><span class="op">(</span><span class="va">country</span><span class="op">)</span> <span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span> <span class="op">(</span> <span class="op">-</span><span class="va">.data</span><span class="op">$</span><span class="va">unique_id_ab_english</span> <span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="op">)</span>
<span class="co">#&gt;       country          weight        </span>
<span class="co">#&gt;  Jordan   : 3295   Min.   : 0.02837  </span>
<span class="co">#&gt;  Lebanon  : 2700   1st Qu.: 0.78310  </span>
<span class="co">#&gt;  Algeria  : 2420   Median : 1.00000  </span>
<span class="co">#&gt;  Palestine: 2400   Mean   : 0.99900  </span>
<span class="co">#&gt;  Tunisia  : 2399   3rd Qu.: 1.08260  </span>
<span class="co">#&gt;  Egypt    : 2396   Max.   :11.26910  </span>
<span class="co">#&gt;  (Other)  :15536                     </span>
<span class="co">#&gt;  evaluation_in_the_last_parliamentary_elections</span>
<span class="co">#&gt;  missing            :7337                      </span>
<span class="co">#&gt;  some_minor_problems:5928                      </span>
<span class="co">#&gt;  free_and_fair      :5509                      </span>
<span class="co">#&gt;  not_free           :5192                      </span>
<span class="co">#&gt;  do_not_know        :3505                      </span>
<span class="co">#&gt;  (Other)            :3075                      </span>
<span class="co">#&gt;  NA's               : 600</span></code></pre></div>
</div>
<div id="analyzing-the-harmonized-surveys-data-of-parliamentary-election-in-mena" class="section level3">
<h3 class="hasAnchor">
<a href="#analyzing-the-harmonized-surveys-data-of-parliamentary-election-in-mena" class="anchor"></a>Analyzing the harmonized survey’s data of parliamentary election in MENA</h3>
<p>From the attributes of the harmonized_ab_waves, we observed unnecessary information that could be omitted such as row names.</p>
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">h_ab_structure</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/attributes.html">attributes</a></span><span class="op">(</span><span class="va">harmonized_arabb_waves</span><span class="op">)</span>
<span class="va">h_ab_structure</span><span class="op">$</span><span class="va">row.names</span> <span class="op">&lt;-</span> <span class="cn">NULL</span> </code></pre></div>
<p>The harmonized data can be exported and analyzed in another statistical program.</p>
<p>The labeled survey data was stored in <code><a href="../reference/labelled_spss_survey.html">labelled_spss_survey()</a></code> vectors, which is a complex class that retains metadata for reproducibility, but most statistical packages work with numeric or categorical (factor) data. The data can be converted to any of these, but you should use the methods of <code><a href="../reference/labelled_spss_survey.html">labelled_spss_survey()</a></code> for this purpose, i.e., <code><a href="../reference/labelled_spss_survey.html">as_numeric()</a></code> or <code><a href="../reference/as_factor.html">as_factor()</a></code>. (See more why you should not fall back on the more generic as.factor() or as.numeric() methods in The <a href="https://retroharmonize.dataobservatory.eu/articles/labelled_spss_survey.html">labelled_spss_survey class vignette</a>.)</p>
<p>Due to the categorical format of the question of MENA parliamentary election evaluation in the Arab Barometer survey rounds, we decided to present the election variable in its <em>categorical format</em>, and disregarded the post-stratification weights.</p>
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">harmonized_arabb_waves</span> <span class="op">&lt;-</span> <span class="va">harmonized_arabb_waves</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>wave <span class="op">=</span> <span class="fu">str_extract</span><span class="op">(</span><span class="va">unique_id_ab_english</span>, <span class="st">"(\\b[A-Z0-9]+)"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">categorical_summary</span> <span class="op">&lt;-</span> <span class="va">harmonized_arabb_waves</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span> <span class="op">(</span> <span class="op">-</span><span class="fu"><a href="https://tidyselect.r-lib.org/reference/all_of.html">all_of</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"weight"</span>, <span class="st">"unique_id_ab_english"</span><span class="op">)</span><span class="op">)</span> <span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span> <span class="op">(</span> 
    evaluation_in_the_last_parliamentary_elections <span class="op">=</span> 
      <span class="fu"><a href="../reference/as_factor.html">as_factor</a></span><span class="op">(</span><span class="va">evaluation_in_the_last_parliamentary_elections</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer</a></span> <span class="op">(</span> <span class="fu"><a href="https://tidyselect.r-lib.org/reference/starts_with.html">starts_with</a></span><span class="op">(</span><span class="st">"evaluation"</span><span class="op">)</span>, 
                 names_to  <span class="op">=</span> <span class="st">"indicator"</span>, 
                 values_to <span class="op">=</span> <span class="st">"valuation"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span> <span class="op">(</span> <span class="va">.data</span><span class="op">$</span><span class="va">country</span>, <span class="va">.data</span><span class="op">$</span><span class="va">wave</span>, <span class="va">.data</span><span class="op">$</span><span class="va">valuation</span> <span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span> <span class="op">(</span>n <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span>,
             .groups <span class="op">=</span> <span class="st">'keep'</span><span class="op">)</span> </code></pre></div>
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">categorical_summary</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">10</span>,<span class="op">]</span>
<span class="co">#&gt; # A tibble: 10 x 4</span>
<span class="co">#&gt; # Groups:   country, wave, valuation [10]</span>
<span class="co">#&gt;    country wave  valuation               n</span>
<span class="co">#&gt;    &lt;chr&gt;   &lt;chr&gt; &lt;fct&gt;               &lt;int&gt;</span>
<span class="co">#&gt;  1 algeria ABI   missing              1300</span>
<span class="co">#&gt;  2 Algeria ABIII not_free              240</span>
<span class="co">#&gt;  3 Algeria ABIII some_major_problems   152</span>
<span class="co">#&gt;  4 Algeria ABIII some_minor_problems   452</span>
<span class="co">#&gt;  5 Algeria ABIII free_and_fair         132</span>
<span class="co">#&gt;  6 Algeria ABIII do_not_know           233</span>
<span class="co">#&gt;  7 Algeria ABIII declined               11</span>
<span class="co">#&gt;  8 Algeria ABIV  not_free              431</span>
<span class="co">#&gt;  9 Algeria ABIV  some_major_problems   151</span>
<span class="co">#&gt; 10 Algeria ABIV  some_minor_problems   237</span></code></pre></div>
<p>The output as shown in the table below indicates the number of votes that were given to each category of the surveys’ parliamentary election question in country and round levels. For instance, the output of the arabbarometric survey round 2 in Algeria shows a high level of dissatisfaction of the last election process with 273 respondents expressed that it was not free, and 155 voters said it had significant problems, while 287 mentioned to some minor problems in the election process, and only 76 opinions indicated that the election process was fair. Furthermore, we notice the high number of ‘do not know’ answers in this round which indicates to some hesitation in respondents’ willingness to express their opinions.This was an example of one country.</p>
</div>
<div id="regional-analysis-of-mena-parliamentary-election-freedom-evaluation" class="section level3">
<h3 class="hasAnchor">
<a href="#regional-analysis-of-mena-parliamentary-election-freedom-evaluation" class="anchor"></a>Regional Analysis of MENA Parliamentary Election Freedom Evaluation</h3>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">regional_parl_elections</span> <span class="op">&lt;-</span> <span class="va">harmonized_arabb_waves</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span>
    <span class="op">-</span><span class="fu"><a href="https://tidyselect.r-lib.org/reference/all_of.html">all_of</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"weight"</span>, <span class="st">"unique_id_ab_english"</span><span class="op">)</span><span class="op">)</span>
    <span class="op">)</span><span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span> <span class="op">(</span> 
    evaluation_in_the_last_parliamentary_elections <span class="op">=</span> 
      <span class="fu"><a href="../reference/as_factor.html">as_factor</a></span><span class="op">(</span><span class="va">evaluation_in_the_last_parliamentary_elections</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer</a></span> <span class="op">(</span> <span class="fu"><a href="https://tidyselect.r-lib.org/reference/starts_with.html">starts_with</a></span><span class="op">(</span><span class="st">"evaluation"</span><span class="op">)</span>, 
                 names_to  <span class="op">=</span> <span class="st">"indicator"</span>, 
                 values_to <span class="op">=</span> <span class="st">"valuation"</span><span class="op">)</span> <span class="op">%&gt;%</span>
      <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">.data</span><span class="op">$</span><span class="va">valuation</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>n<span class="op">=</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> </code></pre></div>
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">regional_parl_elections</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">5</span>,<span class="op">]</span>
<span class="co">#&gt; # A tibble: 5 x 2</span>
<span class="co">#&gt;   valuation               n</span>
<span class="co">#&gt;   &lt;fct&gt;               &lt;int&gt;</span>
<span class="co">#&gt; 1 not_free             5192</span>
<span class="co">#&gt; 2 some_major_problems  2917</span>
<span class="co">#&gt; 3 some_minor_problems  5928</span>
<span class="co">#&gt; 4 free_and_fair        5509</span>
<span class="co">#&gt; 5 do_not_know          3505</span>

<span class="va">regional_not_free</span> <span class="op">&lt;-</span> <span class="va">regional_parl_elections</span><span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">.data</span><span class="op">$</span><span class="va">valuation</span> <span class="op">==</span> <span class="st">'not_free'</span><span class="op">)</span>
<span class="va">regional_maj_prob</span> <span class="op">&lt;-</span> <span class="va">regional_parl_elections</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">.data</span><span class="op">$</span><span class="va">valuation</span> <span class="op">==</span> <span class="st">'some_major_problems'</span><span class="op">)</span>
<span class="va">regional_min_prob</span> <span class="op">&lt;-</span> <span class="va">regional_parl_elections</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">.data</span><span class="op">$</span><span class="va">valuation</span> <span class="op">==</span> <span class="st">'some_minor_problems'</span><span class="op">)</span>
<span class="va">regional_free</span> <span class="op">&lt;-</span> <span class="va">regional_parl_elections</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">.data</span><span class="op">$</span><span class="va">valuation</span> <span class="op">==</span> <span class="st">'Free_and_fair'</span><span class="op">)</span>
<span class="va">regional_dont_know</span> <span class="op">&lt;-</span> <span class="va">regional_parl_elections</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">.data</span><span class="op">$</span><span class="va">valuation</span> <span class="op">==</span> <span class="st">'do_not_know'</span><span class="op">)</span></code></pre></div>
<p>Starting with mentioning that round ABII of the survey has sample size of 12782 voters compared to 14809 of round ABIII and 9000 of round ABIV. We summarized the level of democracy of the parliamentary election process or voters’ satisfaction in MENA region to three tables (see below).</p>
<p>The low democracy level/low satisfaction about the fairness of the election process is presented in the table <code>problama_Elec_process</code>. The total votes that described the process as <em>not-free</em> or <em>with major problems</em> decreased significantly from 44% in 2007-round ABII to less than 30% in 2010-Round ABIV using the total_unfair variable.</p>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## needs review</span>
<span class="va">problem_elec_process</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/bind.html">bind_rows</a></span><span class="op">(</span>
  <span class="va">regional_not_free</span>,
  <span class="va">regional_maj_prob</span>
  <span class="op">)</span>

<span class="va">problem_elec_process</span> <span class="op">&lt;-</span> <span class="va">problem_elec_process</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">.data</span><span class="op">$</span><span class="va">valuation</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>total_unfair <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">.data</span><span class="op">$</span><span class="va">n</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span> <span class="va">.data</span><span class="op">$</span><span class="va">valuation</span>, <span class="va">.data</span><span class="op">$</span><span class="va">total_unfair</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">problem_elec_process</span><span class="op">)</span>
<span class="co">#&gt; # A tibble: 2 x 3</span>
<span class="co">#&gt; # Groups:   valuation [2]</span>
<span class="co">#&gt;   valuation               n total_unfair</span>
<span class="co">#&gt;   &lt;fct&gt;               &lt;int&gt;        &lt;int&gt;</span>
<span class="co">#&gt; 1 not_free             5192         5192</span>
<span class="co">#&gt; 2 some_major_problems  2917         2917</span></code></pre></div>
<p>On the other side, the table<code>Good_Elec_process</code> indicates to a temporarily improvement in absolute number of votes in the round ABIII compared to the round ABII before returning to same level in round ABII, but in percentage scale, the people who expressed that the election was either <em>free and fair</em> or <em>with minor problems</em> increased from 32% in 2010 - round ABII to 47% in 2017- round ABIV using total_fair variable.</p>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R">
<span class="va">Good_Elec_process</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/bind.html">bind_rows</a></span><span class="op">(</span>
  <span class="va">regional_free</span>,
  <span class="va">regional_min_prob</span>
  <span class="op">)</span>

<span class="co">#Good_Elec_process &lt;- Good_Elec_process %&gt;% </span>
<span class="co">#  group_by(.data.$valuation) %&gt;% </span>
<span class="co">#  mutate(total_fair = sum(n)) %&gt;% </span>
<span class="co">#  arrange(.data$valuation,.data$total_fair)</span>
<span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">Good_Elec_process</span><span class="op">)</span>
<span class="co">#&gt; # A tibble: 1 x 2</span>
<span class="co">#&gt;   valuation               n</span>
<span class="co">#&gt;   &lt;fct&gt;               &lt;int&gt;</span>
<span class="co">#&gt; 1 some_minor_problems  5928</span></code></pre></div>
<p>The rest of the people who responded to this question with “I do not know” increased from 11.3% in 2007 to 15.6% in 2010.</p>
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">reluctant_respondents</span> <span class="op">&lt;-</span> <span class="va">regional_dont_know</span>
<span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">reluctant_respondents</span><span class="op">)</span>
<span class="co">#&gt; # A tibble: 1 x 2</span>
<span class="co">#&gt;   valuation       n</span>
<span class="co">#&gt;   &lt;fct&gt;       &lt;int&gt;</span>
<span class="co">#&gt; 1 do_not_know  3505</span></code></pre></div>
<p>Eventually, users can go deeper in analyzing the harmonized data of our question about the parliamentary election process in MENA, and they can test the library on other questions to reach and explore other interesting results. The main purpose of this blog was to show the power of <strong>retroharmonize</strong> in handling large and complex survey data in a way that help users to obtain the required output effectively.</p>
<p>The <code><a href="../reference/merge_waves.html">merge_waves()</a></code> function harmonizes the variable names, the variable labels and survey identifiers and returns a list of surveys (of class <code><a href="../reference/survey.html">survey()</a></code>.) The parameter <code>var_harmonization</code> must be a list or a data frame that contains at least the original file name (<code>filename</code>), original variable names (<code>var_name_orig</code>), the new variable names (<code>var_name</code>) and their labels (<code>var_label</code>), so that the program knows which variables to take from what files and how to call and label them after transformation.</p>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">merged_ab</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/merge_waves.html">merge_waves</a></span> <span class="op">(</span> waves <span class="op">=</span> <span class="va">arab_waves</span>, 
                           var_harmonization <span class="op">=</span> <span class="va">to_harmonize</span>  <span class="op">)</span>

<span class="co"># country will be a character variable, and doesn't need a label</span>
<span class="va">merged_ab</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span> <span class="op">(</span> <span class="va">merged_ab</span>, 
         FUN <span class="op">=</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="va">x</span>  <span class="op">%&gt;%</span>
           <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span> country <span class="op">=</span> <span class="fu"><a href="../reference/labelled_spss_survey.html">as_character</a></span><span class="op">(</span><span class="va">country</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>Review the most important metadata with <code><a href="../reference/document_waves.html">document_waves()</a></code>:</p>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">documenteded_merged_ab</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/document_waves.html">document_waves</a></span><span class="op">(</span><span class="va">merged_ab</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">documenteded_merged_ab</span><span class="op">)</span>
<span class="co">#&gt; # A tibble: 5 x 5</span>
<span class="co">#&gt;   id               filename           ncol  nrow object_size</span>
<span class="co">#&gt;   &lt;chr&gt;            &lt;chr&gt;             &lt;int&gt; &lt;int&gt;       &lt;dbl&gt;</span>
<span class="co">#&gt; 1 Arab_Barometer_5 AB-WaveV-EN.sav       4 26780     2986800</span>
<span class="co">#&gt; 2 Arab_Barometer_1 ABI_English.sav       2  7337      690576</span>
<span class="co">#&gt; 3 Arab_Barometer_2 ABII_English.sav      4 12782     1437856</span>
<span class="co">#&gt; 4 Arab_Barometer_3 ABIII_English.sav     5 14809     1785672</span>
<span class="co">#&gt; 5 Arab_Barometer_4 ABIV_English.sav      4  9000     1013488</span></code></pre></div>
<p>The files we want to harmonize must contain the same variables. If we want to weight the answers, we should either drop Arab-Barometer_1, or for simplicity, add weight = 1 to this survey.</p>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## not evaluated, this is how to drop the Arab-Barometer_1</span>
<span class="va">merged_ab</span><span class="op">[[</span><span class="fl">2</span><span class="op">]</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></code></pre></div>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">merged_ab</span><span class="op">[[</span><span class="fl">2</span><span class="op">]</span><span class="op">]</span><span class="op">$</span><span class="va">weight</span> <span class="op">&lt;-</span> <span class="fl">1</span></code></pre></div>
<p>Similarly, we can either drop the date of the interview or fill it up with, for example, the middle day of the surveying period.</p>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">merged_arabb</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span> <span class="op">(</span> <span class="va">merged_ab</span>, <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">{</span>
  <span class="kw">if</span> <span class="op">(</span> <span class="st">"date_of_interview"</span> <span class="op">%in%</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="op">)</span> <span class="op">{</span>
    <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span> <span class="op">(</span> <span class="va">x</span>, select <span class="op">=</span> <span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">date_of_interview</span><span class="op">)</span><span class="op">)</span>
  <span class="op">}</span> <span class="kw">else</span> <span class="op">{</span>
    <span class="co">## subset works with survey class, if omitted, will return </span>
    <span class="co">## data frame without metadata</span>
    <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span> <span class="op">(</span> <span class="va">x</span> <span class="op">)</span>
  <span class="op">}</span>
<span class="op">}</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">documenteded_merged_arabb</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/document_waves.html">document_waves</a></span><span class="op">(</span><span class="va">merged_arabb</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">documenteded_merged_arabb</span><span class="op">)</span>
<span class="co">#&gt; # A tibble: 5 x 5</span>
<span class="co">#&gt;   id               filename           ncol  nrow object_size</span>
<span class="co">#&gt;   &lt;chr&gt;            &lt;chr&gt;             &lt;int&gt; &lt;int&gt;       &lt;dbl&gt;</span>
<span class="co">#&gt; 1 Arab_Barometer_5 AB-WaveV-EN.sav       3 26780     2771984</span>
<span class="co">#&gt; 2 Arab_Barometer_1 ABI_English.sav       3  7337      749408</span>
<span class="co">#&gt; 3 Arab_Barometer_2 ABII_English.sav      4 12782     1437856</span>
<span class="co">#&gt; 4 Arab_Barometer_3 ABIII_English.sav     4 14809     1666176</span>
<span class="co">#&gt; 5 Arab_Barometer_4 ABIV_English.sav      4  9000     1013488</span></code></pre></div>
<p>Now we have the same four variables in each wave: unique id ab english, country, weight.</p>
</div>
</div>
<div id="harmonization" class="section level2">
<h2 class="hasAnchor">
<a href="#harmonization" class="anchor"></a>Harmonization</h2>
<p>To review the harmonization on a single survey use <code><a href="../reference/pull_survey.html">pull_survey()</a></code>. Here we select Arab Barometer Round 3.</p>
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">R3</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/pull_survey.html">pull_survey</a></span> <span class="op">(</span> <span class="va">merged_ab</span>, id <span class="op">=</span> <span class="st">"Arab_Barometer_3"</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/attributes.html">attributes</a></span><span class="op">(</span><span class="va">R3</span><span class="op">$</span><span class="va">evaluation_economic_situation</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">20</span><span class="op">]</span><span class="op">)</span>
<span class="co">#&gt; Warning: Unknown or uninitialised column: `evaluation_economic_situation`.</span>
<span class="co">#&gt; NULL</span></code></pre></div>
<p>The <code><a href="../reference/document_survey_item.html">document_survey_item()</a></code> function shows the metadata of a single variable.</p>
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/document_survey_item.html">document_survey_item</a></span><span class="op">(</span><span class="va">R3</span><span class="op">$</span><span class="va">evaluation_economic_situation</span><span class="op">)</span>
<span class="co">#&gt; Warning: Unknown or uninitialised column: `evaluation_economic_situation`.</span>
<span class="co">#&gt; $code_table</span>
<span class="co">#&gt; # A tibble: 0 x 1</span>
<span class="co">#&gt; # ... with 1 variable: missing &lt;lgl&gt;</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $history_var_name</span>
<span class="co">#&gt;                               name </span>
<span class="co">#&gt; "R3$evaluation_economic_situation" </span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $history_var_label</span>
<span class="co">#&gt; character(0)</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $history_na_range</span>
<span class="co">#&gt; character(0)</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $history_id</span>
<span class="co">#&gt; NULL</span></code></pre></div>
<p>Arab Barometer’s SPSS files do not mark the missing values, so we have to be careful.</p>
<p>The set of valid category labels and missing value labels are as follows:</p>
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/collect_val_labels.html">collect_val_labels</a></span> <span class="op">(</span><span class="va">to_harmonize</span> <span class="op">%&gt;%</span>
                      <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span> <span class="op">(</span> <span class="fu"><a href="https://rdrr.io/r/base/grep.html">grepl</a></span><span class="op">(</span> <span class="st">"evaluation_economic_situation"</span>, <span class="va">var_name</span><span class="op">)</span> <span class="op">)</span><span class="op">)</span>
<span class="co">#&gt; character(0)</span></code></pre></div>
<p>Apparently, there are a number of missing value labels here, and it is not even always clear if they refer to the same type of “missingness” with the same word.</p>
<p>In the examples with <a href="https://retroharmonize.dataobservatory.eu/articles/afrobarometer.html">Afrobarometer</a> and <a href="https://retroharmonize.dataobservatory.eu/articles/eurobarometer.html">Eurobarometer</a>, we saw different problems with missing variables.</p>
<ul>
<li>In Eurobarometer, the type of missingness is relatively clear, and in the SPSS files, the missing labels are usually, but not always identified.</li>
<li>In Afrobarometer, the missing classes are clear, but the SPSS missing labels are not used. Instead the SPSS missing range (<code>na_range</code>) is used, but sometimes inconsistently with the missing labels (<code>na_labels</code>).</li>
</ul>
<p>In some statistical analysis, these differences do not matter much (for example, when creating averages from numeric values or numeric representations), but when you work with categories or you examine the survey’s quality, these differences can be important.</p>
<p>We create a harmonization function from the <code><a href="../reference/harmonize_values.html">harmonize_values()</a></code> prototype function. In fact, this is just a re-setting the default values of the original function. It makes future reference in pipelines easier, or it can be used for a question block only, in this case to variables with <code><a href="https://tidyselect.r-lib.org/reference/starts_with.html">starts_with("trust")</a></code>.</p>
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">harmonize_arabb_trust</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="op">{</span>
  <span class="va">label_list</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>
    from <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"very\\sgood"</span>, <span class="st">"(?&lt;!very\\s)good"</span>,
             <span class="st">"(?&lt;!very\\s)bad"</span>, <span class="st">"very\\sbad"</span>, 
             <span class="st">"t\\sknow"</span>, <span class="st">"refuse"</span>, <span class="st">"decline"</span>, <span class="st">"missing"</span><span class="op">)</span>, 
    to <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"very_good"</span>, <span class="st">"good"</span>, <span class="st">"bad"</span>, 
           <span class="st">"very_bad"</span>, <span class="st">"do_not_know"</span>, 
           <span class="st">"declined"</span>, <span class="st">"declined"</span>, <span class="st">"missing"</span><span class="op">)</span>, 
    numeric_values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>,<span class="fl">2</span>,<span class="fl">1</span>,<span class="fl">0</span>, <span class="fl">99997</span>, <span class="fl">99998</span>, <span class="fl">99998</span>,<span class="fl">99999</span><span class="op">)</span>
  <span class="op">)</span>
  
  <span class="fu"><a href="../reference/harmonize_values.html">harmonize_values</a></span><span class="op">(</span>
    <span class="va">x</span>, 
    harmonize_labels <span class="op">=</span> <span class="va">label_list</span>, 
    na_values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"do_not_know"</span><span class="op">=</span><span class="fl">99997</span>,
                  <span class="st">"declined"</span><span class="op">=</span><span class="fl">99998</span>,
                  <span class="st">"missing"</span><span class="op">=</span><span class="fl">99999</span><span class="op">)</span>, 
    perl <span class="op">=</span> <span class="cn">TRUE</span>
  <span class="op">)</span>
<span class="op">}</span></code></pre></div>
<p>Let’s see if the output makes sense:</p>
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># review this</span>
<span class="co"># We only print a random sample from the results.</span>
<span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">2020</span><span class="op">)</span>
<span class="fu">harmonize_arabb_trust</span><span class="op">(</span>
  <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="va">R3</span><span class="op">$</span><span class="va">evaluation_economic_situation</span>, <span class="fl">12</span><span class="op">)</span>
<span class="op">)</span></code></pre></div>
<p>We apply this function to the trust variables. The <code><a href="../reference/harmonize_waves.html">harmonize_waves()</a></code> function binds all variables that are present in all surveys.</p>
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">harmonized_arabb_waves</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/harmonize_waves.html">harmonize_waves</a></span> <span class="op">(</span> 
  waves <span class="op">=</span> <span class="va">merged_arabb</span>, 
  .f <span class="op">=</span> <span class="va">harmonize_arabb_trust</span> <span class="op">)</span> </code></pre></div>
<p>Let’s look at the attributes of <code>harmonized_arabb_waves</code>.</p>
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">h_arabb_structure</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/attributes.html">attributes</a></span><span class="op">(</span><span class="va">harmonized_arabb_waves</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">h_arabb_structure</span><span class="op">$</span><span class="va">row.names</span> <span class="op">&lt;-</span> <span class="cn">NULL</span> <span class="co"># We have over 70K row names</span>
<span class="va">h_arabb_structure</span></code></pre></div>
<p>To keep our example manageable, we subset the datasets to include only five countries.</p>
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">harmonized_arabb_waves</span> <span class="op">&lt;-</span> <span class="va">harmonized_arabb_waves</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span> <span class="op">(</span> id <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/strsplit.html">strsplit</a></span><span class="op">(</span><span class="va">unique_id_ab_english</span>, <span class="st">"[_]"</span><span class="op">)</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">)</span></code></pre></div>
</div>
<div id="analyzing-the-harmonized-data" class="section level2">
<h2 class="hasAnchor">
<a href="#analyzing-the-harmonized-data" class="anchor"></a>Analyzing the harmonized data</h2>
<p>The harmonized data can be exported and analyzed in another statistical program. The labelled survey data is stored in <code><a href="../reference/labelled_spss_survey.html">labelled_spss_survey()</a></code> vectors, which is a complex class that retains metadata for reproducibility. Most statistical R packages do not know it. The data should be presented either as numeric data with <code><a href="../reference/labelled_spss_survey.html">as_numeric()</a></code> or as categorical with <code><a href="../reference/as_factor.html">as_factor()</a></code>. (See more why you should not fall back on the more generic <code><a href="https://rdrr.io/r/base/factor.html">as.factor()</a></code> or <code><a href="https://rdrr.io/r/base/numeric.html">as.numeric()</a></code> methods in <a href="https://retroharmonize.dataobservatory.eu/articles/labelled_spss_survey.html">The labelled_spss_survey class vignette.</a>)</p>
<p>Please note that the numeric form of these trust variables is not directly comparable with the numeric averages of the Eurobarometer trust variables, because the middle of the range is at 1.5 and not 0.5.</p>
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">numeric_summary</span> <span class="op">&lt;-</span> <span class="va">harmonized_arabb_waves</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate_all.html">mutate_at</a></span> <span class="op">(</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/vars.html">vars</a></span><span class="op">(</span><span class="fu"><a href="https://tidyselect.r-lib.org/reference/starts_with.html">starts_with</a></span><span class="op">(</span><span class="st">"evaluation"</span><span class="op">)</span><span class="op">)</span>, 
              <span class="op">~</span><span class="fu"><a href="../reference/labelled_spss_survey.html">as_numeric</a></span><span class="op">(</span><span class="va">.</span><span class="op">)</span><span class="op">*</span><span class="va">weight</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span> <span class="op">(</span> <span class="op">-</span><span class="fu"><a href="https://tidyselect.r-lib.org/reference/all_of.html">all_of</a></span><span class="op">(</span><span class="st">"weight"</span><span class="op">)</span> <span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span> <span class="op">(</span> <span class="va">.data</span><span class="op">$</span><span class="va">country</span> <span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise_all.html">summarize_if</a></span> <span class="op">(</span> <span class="va">is.numeric</span>, <span class="va">mean</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span> <span class="op">)</span>

<span class="va">numeric_summary</span>
<span class="co">#&gt; # A tibble: 19 x 2</span>
<span class="co">#&gt;    country   evaluation_in_the_last_parliamentary_elections</span>
<span class="co">#&gt;    &lt;chr&gt;                                              &lt;dbl&gt;</span>
<span class="co">#&gt;  1 algeria                                          NaN    </span>
<span class="co">#&gt;  2 Algeria                                            1.24 </span>
<span class="co">#&gt;  3 bahrain                                          NaN    </span>
<span class="co">#&gt;  4 Egypt                                              1.71 </span>
<span class="co">#&gt;  5 Iraq                                               1.45 </span>
<span class="co">#&gt;  6 jordan                                           NaN    </span>
<span class="co">#&gt;  7 Jordan                                             1.19 </span>
<span class="co">#&gt;  8 Kuwait                                             2.11 </span>
<span class="co">#&gt;  9 lebanon                                          NaN    </span>
<span class="co">#&gt; 10 Lebanon                                            1.50 </span>
<span class="co">#&gt; 11 Libya                                              1.78 </span>
<span class="co">#&gt; 12 morocco                                          NaN    </span>
<span class="co">#&gt; 13 Morocco                                            1.55 </span>
<span class="co">#&gt; 14 palestine                                        NaN    </span>
<span class="co">#&gt; 15 Palestine                                          2.04 </span>
<span class="co">#&gt; 16 Sudan                                              1.26 </span>
<span class="co">#&gt; 17 Tunisia                                            2.05 </span>
<span class="co">#&gt; 18 yemen                                            NaN    </span>
<span class="co">#&gt; 19 Yemen                                              0.998</span></code></pre></div>
<p>And the factor representation, without weighting:</p>
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyr.tidyverse.org">tidyr</a></span><span class="op">)</span>  <span class="co">## tidyr::pivot_longer()</span>
<span class="va">categorical_summary</span> <span class="op">&lt;-</span> <span class="va">harmonized_arabb_waves</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span> <span class="op">(</span> <span class="op">-</span><span class="fu"><a href="https://tidyselect.r-lib.org/reference/all_of.html">all_of</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"weight"</span>, <span class="st">"unique_id_ab_english"</span><span class="op">)</span><span class="op">)</span> <span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span> <span class="op">(</span> 
    evaluation_economic_situation <span class="op">=</span> 
      <span class="fu"><a href="../reference/as_factor.html">as_factor</a></span><span class="op">(</span><span class="va">evaluation_economic_situation</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer</a></span> <span class="op">(</span> <span class="fu"><a href="https://tidyselect.r-lib.org/reference/starts_with.html">starts_with</a></span><span class="op">(</span><span class="st">"evaluation"</span><span class="op">)</span>, 
                        names_to  <span class="op">=</span> <span class="st">"indicator"</span>, 
                        values_to <span class="op">=</span> <span class="st">"valuation"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span> <span class="op">(</span> <span class="va">.data</span><span class="op">$</span><span class="va">country</span>, <span class="va">.data</span><span class="op">$</span><span class="va">valuation</span> <span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span> <span class="op">(</span> n <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span> <span class="op">)</span> 

<span class="va">categorical_summary</span></code></pre></div>
<div id="saved-variables" class="section level3">
<h3 class="hasAnchor">
<a href="#saved-variables" class="anchor"></a>Saved Variables</h3>
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">haven</span><span class="fu">::</span><span class="fu"><a href="https://haven.tidyverse.org/reference/read_spss.html">write_sav</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">harmonized_arabb_waves</span>, <span class="st">"harmonized_arabb_waves.sav"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/write.table.html">write.csv</a></span><span class="op">(</span><span class="va">harmonized_arabb_waves</span>, <span class="st">"harmonized_arabb_waves.csv"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/write.table.html">write.csv</a></span><span class="op">(</span><span class="va">categorical_summary</span>, <span class="st">"categorical_summary.csv"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/write.table.html">write.csv</a></span><span class="op">(</span><span class="va">numeric_summary</span>, <span class="st">"numeric_summary.csv"</span><span class="op">)</span>

<span class="co"># The metadata file contains list objects, which cannot be represented</span>
<span class="co"># in a flat csv file format.</span>
<span class="fu"><a href="https://rdrr.io/r/base/readRDS.html">saveRDS</a></span><span class="op">(</span><span class="va">arabb_metadata</span>, <span class="st">"arabb_metadata.rds"</span><span class="op">)</span>

<span class="co">## The lists of value labels are dropped from the csv output.</span>
<span class="fu"><a href="https://rdrr.io/r/utils/write.table.html">write.csv</a></span><span class="op">(</span><span class="va">arabb_metadata</span> <span class="op">[</span>, <span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span> <span class="op">(</span> <span class="va">arabb_metadata</span>, <span class="va">class</span><span class="op">)</span> <span class="op">==</span> <span class="st">"list"</span><span class="op">)</span><span class="op">]</span>, <span class="st">"arabb_metadata_simplified.csv"</span><span class="op">)</span></code></pre></div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Daniel Antal.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
